### ISSUE TITLE
Agrupar projetos elétrico

### ISSUE THREAD

**Issue by miriamlleite** [marceloduartesilva/PSA_Proj_Kuka#12]

**Comment by Pedrokrc** [comment]
baseei-me no esquema eletrico do modelo KR C2 edition2005

**Comment by miriamlleite** [comment]
Projeto elétrico /Marcelo

[Esquema_Célula_PSA.pdf](https://github.com/marceloduartesilva/PSA_Proj_Kuka/files/9067155/Esquema_Celula_PSA.pdf)
