### ISSUE TITLE
PE_Câmera P2X

### ISSUE THREAD

**Issue by miriamlleite** [marceloduartesilva/PSA_Proj_Kuka#7]
DataLogic

**Comment by iagobritofreitas** [comment]
found a manual for the camera on this website: https://www.hiv-hoffmann.de/wp-content/uploads/2021/04/P2x-Series-Product-Reference-Guide-eng.pdf

**Comment by iagobritofreitas** [comment]
downloaded the impact lite software on this website: https://www.oem.co.uk/products/machine-vision-,-a-,-code-reading/machine-vision-software/datalogic-_-429792/datalogic---impact-vision-software-_-511518

**Comment by iagobritofreitas** [comment]
studying the software's manual found on this link: https://www.oem.co.uk/ui/product-resources/oem/-_-135095.pdf?att=False&hash=F27BD117E81287C2901BA93EE232C763

**Comment by iagobritofreitas** [comment]
here there is the solution for the problem about identifying keys, proposed by professor Abílio.
[Key detection solution VPM.zip](https://github.com/marceloduartesilva/PSA_Proj_Kuka/files/8513649/Key.detection.solution.VPM.zip)
.

**Comment by miriamlleite** [comment]
Foi alterada a Câmara a utilizar
